# LINUX_OVERRIDE_SRCDIR=$(TOPDIR)/../$(BR2_LINUX_KERNEL_VERSION)
GCC_OVERRIDE_SRCDIR = $(TOPDIR)/../gcc-12.3.0
GCC_INITIAL_OVERRIDE_SRCDIR = $(GCC_OVERRIDE_SRCDIR)
GCC_FINAL_OVERRIDE_SRCDIR = $(GCC_OVERRIDE_SRCDIR)
